services:

  mysql:
    container_name: mysql
    build: ./repositories/mysql_database
    restart: always
    ports: 
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  flask_api:
    build: ./repositories/flask_api
    volumes:
      - ./repositories/flask_api/:/app
    environment:
      - DB_USER=root
      - DB_HOST=mysql
      - DB_PASS=pass
      - MYSQL_DATABASE=my_database
    ports:
      - 5000:5000
    
    depends_on:
      - mysql
    stdin_open: true
    tty: true

volumes:
  db_data: